# Generated by Django 4.0.4 on 2022-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_request_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_book',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
