# Generated by Django 4.0.4 on 2022-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_request_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_book',
            name='book_link',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
