# Generated by Django 4.0.4 on 2022-04-17 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_request_book_book_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_book',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
