# Generated by Django 4.0.4 on 2022-04-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_request_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_book',
            name='book_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
