# Generated by Django 4.0.4 on 2022-04-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldcoffee',
            name='amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
